name: to_curl
description: Fork from https://github.com/kiruto/curl . Generate output equivalent to the "copy as curl" option with HTTP client debugger. 
version: 2.0.0-nullsafety.0
homepage: https://github.com/talisk/curl

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.10
